#!/usr/bin/env bash
# Display "To infinity and beyond" indefinitely
# bash sleeps for 2 seconds after each loop

i=1
var="To infinity and beyond"
var2="I am invincible!!!"
while [ $i -eq 1 ]
do
	echo "$var"
	sleep 2
	trap 'echo "$var2"' SIGTERM
done
